#! /bin/sh

rm -r cs-cj/
mkdir cs-cj/

fella -o cs-cj/f-empower.coffee cs/f-empower.coffee

coffee -o dist/ -cb cs/
coffee -o dist-cj/ -cb cs-cj/

uglifyjs -m -o dist/f-empower.min.js dist/f-empower.js

gzip -fk9 dist/f-empower.min.js

echo "Build complete"
