// Generated by CoffeeScript 1.7.1
var assert, clonedeep2, consoleline, debounce, each, equal, equal_deep, fs, functions, inc, is_plain_object, map, merge, print_json, push, slice, sumn, test_clonedeep2, test_debounce, test_each, test_is_plain_object, test_map, test_merge, test_throttle, throttle;

functions = require('./f-empower');

fs = require('fs');

assert = require('assert');

consoleline = function() {
  return console.log("");
};

clonedeep2 = functions.clonedeep2, debounce = functions.debounce, each = functions.each, is_plain_object = functions.is_plain_object, inc = functions.inc, map = functions.map, merge = functions.merge, push = functions.push, slice = functions.slice, sumn = functions.sumn, throttle = functions.throttle;

print_json = function(obj) {
  return console.log(JSON.stringify(obj, null, 2));
};

equal = assert.equal;

equal_deep = assert.deepEqual;

test_clonedeep2 = function() {
  var cloned, tree;
  tree = JSON.parse(fs.readFileSync('tree.json', 'utf-8'));
  cloned = clonedeep2(tree);
  return print_json(cloned);
};

test_each = function() {
  var results, write_result;
  console.log("testing each");
  results = null;
  write_result = function() {
    return push(results, slice(arguments));
  };
  results = [];
  each(write_result, [1, 2, 3]);
  equal_deep(results, [[1], [2], [3]]);
  console.log("each:arity 2 is ok");
  results = [];
  each(write_result, [1, 2], [1, 2, 3]);
  equal_deep(results, [[1, 1], [2, 2]]);
  results = [];
  each(write_result, [1, 2, 3], [1, 2, 3]);
  equal_deep(results, [[1, 1], [2, 2], [3, 3]]);
  console.log("each:arity 3 is ok");
  results = [];
  each(write_result, [1, 2], [1, 2, 3], [1, 2, 3]);
  equal_deep(results, [[1, 1, 1], [2, 2, 2]]);
  results = [];
  each(write_result, [1, 2, 3], [1, 2, 3], [1, 2, 3]);
  equal_deep(results, [[1, 1, 1], [2, 2, 2], [3, 3, 3]]);
  console.log("each:arity n is ok");
  return consoleline();
};

test_map = function() {
  console.log("testing map");
  equal(sumn(1, 2), 3);
  equal(sumn(1, 2, 3, 4), 10);
  console.log("helper function is ok");
  equal_deep(map(inc, [0, 1, 2]), [1, 2, 3]);
  console.log("map:arity 2 is ok");
  equal_deep(map(sumn, [1, 2], [1]), [2]);
  equal_deep(map(sumn, [1, 2], [1, 2]), [2, 4]);
  console.log("map:arity 3 is ok");
  equal_deep(map(sumn, [1, 2], [1, 2, 3], [1, 2, 3]), [3, 6]);
  equal_deep(map(sumn, [1, 2, 3], [1, 2, 3], [1, 2, 3]), [3, 6, 9]);
  console.log("map:arity n is ok");
  return consoleline();
};

test_merge = function() {
  var Editor, Editor2, a, b, result;
  b = {
    foo: 'bar',
    editor: 'vim',
    city: 'Moscow'
  };
  b.loop = b;
  result = merge({}, b);
  assert(result.loop.loop.loop === result.loop);
  Editor = (function() {
    function Editor(name) {
      this.name = name;
    }

    return Editor;

  })();
  Editor2 = (function() {
    function Editor2(name) {
      this.name = name;
    }

    return Editor2;

  })();
  a = {
    editor: 'vim',
    ctor_opts: {
      ctor: Editor
    },
    plugins: {
      tabs: true,
      coffeescript: true,
      clojure: true
    },
    array: ["should", "also", "be", "merged"]
  };
  b = {
    editor: 'emacs',
    ctor_opts: {
      ctor: Editor2
    },
    plugins: {
      tabs: false,
      coffeescript: false,
      javascript: true
    },
    array: ["don't"]
  };
  result = merge(a, b);
  return assert.deepEqual(result, {
    editor: 'emacs',
    ctor_opts: {
      ctor: Editor2
    },
    plugins: {
      tabs: false,
      coffeescript: false,
      clojure: true,
      javascript: true
    },
    array: ["don't", "also", "be", "merged"]
  });
};

test_is_plain_object = function() {
  var Python, sammy;
  Python = (function() {
    function Python(length) {
      this.length = length;
    }

    return Python;

  })();
  sammy = new Python(4);
  assert(!(is_plain_object(sammy)));
  return assert(is_plain_object({
    editor: 'vim'
  }));
};

test_debounce = function(next) {
  var a, dfn, fn;
  console.log("testing debounce");
  a = 0;
  fn = function() {
    return ++a * 2;
  };
  dfn = debounce(100, fn);
  equal(dfn(), void 0);
  setTimeout(function() {
    return equal(dfn(), 2);
  }, 100);
  return setTimeout(function() {
    equal(dfn(), 4);
    console.log("debounce is ok");
    consoleline();
    return next && next();
  }, 202);
};

test_throttle = function() {
  return console.log("testing throttle");
};

test_each();

test_map();

test_merge();

test_is_plain_object();

test_debounce(function() {
  return test_throttle();
});
